;SRCの設定ファイルです。
;項目の内容に関してはヘルプの
; 操作方法 => マップコマンド => 設定変更
;の項を参照して下さい。

[Option]
;メッセージのウェイト。標準は700
MessageWait=700

;ターン数の表示 [On|Off]
Turn=Off

;マス目の表示 [On|Off]
Square=Off

;敵フェイズにはＢＧＭを変更しない [On|Off]
KeepEnemyBGM=Off

;自動防御モード [On|Off]
AutoDefense=Off

;自動カーソル移動 [On|Off]
AutoMoveCursor=On

;スペシャルパワーアニメ [On|Off]
SpecialPowerAnimation=On

;戦闘アニメ [On|Off]
BattleAnimation=On

;戦闘アニメの拡張機能 [On|Off]
ExtendedAnimation=On

;武器準備アニメの自動選択表示 [On|Off]
WeaponAnimation=On

;移動アニメ [On|Off]
MoveAnimation=On

;MIDI音源リセットの種類 [None|GM|GS|XG]
MidiReset=None

;MIDI演奏にDirectMusicを使う [On|Off]
UseDirectMusic=Off

;DirectMusicで使うMIDI音源のポート番号 [自動検索=0]
MIDIPortID=0

;MP3再生時の音量 (0～100)
MP3Volume=50

;MP3の出力フレーム数
MP3OutputBlock=20

;MP3の入力直後のスリープ時間(ミリ秒)
MP3IutputSleep=5

;WAV再生にDirectSoundを使う [On|Off]
UseDirectSound=On

;画像バッファの枚数
ImageBufferNum=64

;画像バッファの最大サイズ (MB)
MaxImageBufferSize=8

;拡大画像を画像バッファに保存する [On|Off]
KeepStretchedImage=

;透過描画にAPI関数TransparentBltを使う [On|Off]
UseTransparentBlt=On

;拡張データのフォルダ (フルパスで指定)
ExtDataPath=
ExtDataPath2=

;デバッグモード [On|Off]
DebugMode=Off

;新ＧＵＩ(テスト中) [On|Off]
NewGUI=Off

[Log]
;前回使用したフォルダ
LastFolder=

[BGM]
;SRC起動時
Opening=Opening.mid
;味方フェイズ開始時
Map1=Map1.mid
;敵フェイズ開始時
Map2=Map2.mid
;屋内マップの味方フェイズ開始時
Map3=Map3.mid
;屋内マップの敵フェイズ開始時
Map4=Map4.mid
;宇宙マップの味方フェイズ開始時
Map5=Map5.mid
;宇宙マップの敵フェイズ開始時
Map6=Map6.mid
;プロローグ・エピローグ開始時
Briefing=Briefing.mid
;インターミッション開始時
Intermission=Intermission.mid
;テロップ表示時
Subtitle=Subtitle.mid
;ゲームオーバー時
End=End.mid
;戦闘時のデフォルトMIDI
default=default.mid

