using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class BGClass_ImportedFonts : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BGClass_ImportedFonts(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BGClass_ImportedFonts(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5394091832305173659UL,15825802688521098940UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String BG_name
	{
		get => _BG_name[Index];
		set => _BG_name[Index] = value;
	}
	public System.String BG_FilePath
	{
		get => _BG_FilePath[Index];
		set => _BG_FilePath[Index] = value;
	}
	public System.Int32 BG_Next
	{
		get => _BG_Next[Index];
		set => _BG_Next[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_BG_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _BG_name => _ufle12jhs77_BG_name ?? (_ufle12jhs77_BG_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5491788736441075098UL, 9942495857176704684UL), () => _ufle12jhs77_BG_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_BG_FilePath;
	public static BansheeGz.BGDatabase.BGFieldString _BG_FilePath => _ufle12jhs77_BG_FilePath ?? (_ufle12jhs77_BG_FilePath = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5012169299209808125UL, 11947896336987441076UL), () => _ufle12jhs77_BG_FilePath = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_BG_Next;
	public static BansheeGz.BGDatabase.BGFieldInt _BG_Next => _ufle12jhs77_BG_Next ?? (_ufle12jhs77_BG_Next = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5233077079295538586UL, 4239875578567192449UL), () => _ufle12jhs77_BG_Next = null));
	private static readonly BGClass_ImportedFonts.Factory _factory0_PFS = new BGClass_ImportedFonts.Factory();
	private static readonly BGClass_ImportedFontsCommit.Factory _factory1_PFS = new BGClass_ImportedFontsCommit.Factory();
	private BGClass_ImportedFonts() : base(MetaDefault)
	{
	}
	private BGClass_ImportedFonts(BGId id) : base(MetaDefault, id)
	{
	}
	private BGClass_ImportedFonts(BGMetaEntity meta) : base(meta)
	{
	}
	private BGClass_ImportedFonts(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BGClass_ImportedFonts FindEntity(Predicate<BGClass_ImportedFonts> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((BGClass_ImportedFonts) entity)) as BGClass_ImportedFonts;
	}
	public static List<BGClass_ImportedFonts> FindEntities(Predicate<BGClass_ImportedFonts> filter, List<BGClass_ImportedFonts> result=null, Comparison<BGClass_ImportedFonts> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BGClass_ImportedFonts> action, Predicate<BGClass_ImportedFonts> filter=null, Comparison<BGClass_ImportedFonts> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((BGClass_ImportedFonts) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BGClass_ImportedFonts) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BGClass_ImportedFonts)e1,(BGClass_ImportedFonts)e2));
	}
	public static BGClass_ImportedFonts GetEntity(BGId entityId) => (BGClass_ImportedFonts) MetaDefault.GetEntity(entityId);
	public static BGClass_ImportedFonts GetEntity(int index) => (BGClass_ImportedFonts) MetaDefault[index];
	public static BGClass_ImportedFonts GetEntity(string entityName) => (BGClass_ImportedFonts) MetaDefault.GetEntity(entityName);
	public static BGClass_ImportedFonts NewEntity() => (BGClass_ImportedFonts) MetaDefault.NewEntity();
	public static BGClass_ImportedFonts NewEntity(BGId entityId) => (BGClass_ImportedFonts) MetaDefault.NewEntity(entityId);
	public static BGClass_ImportedFonts NewEntity(Action<BGClass_ImportedFonts> callback)
	{
		return (BGClass_ImportedFonts) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BGClass_ImportedFonts)entity)));
	}
}

public partial class BGClass_ImportedFontsCommit : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new BGClass_ImportedFontsCommit(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new BGClass_ImportedFontsCommit(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5698365174517956776UL,4377561417327406011UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String BG_name
	{
		get => _BG_name[Index];
		set => _BG_name[Index] = value;
	}
	public System.String BG_FilePath
	{
		get => _BG_FilePath[Index];
		set => _BG_FilePath[Index] = value;
	}
	public System.Int32 BG_Next
	{
		get => _BG_Next[Index];
		set => _BG_Next[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_BG_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _BG_name => _ufle12jhs77_BG_name ?? (_ufle12jhs77_BG_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5165186123815129994UL, 3682541195757062075UL), () => _ufle12jhs77_BG_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_BG_FilePath;
	public static BansheeGz.BGDatabase.BGFieldString _BG_FilePath => _ufle12jhs77_BG_FilePath ?? (_ufle12jhs77_BG_FilePath = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5378120277811624140UL, 4082224575315318207UL), () => _ufle12jhs77_BG_FilePath = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_BG_Next;
	public static BansheeGz.BGDatabase.BGFieldInt _BG_Next => _ufle12jhs77_BG_Next ?? (_ufle12jhs77_BG_Next = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5444389343373439259UL, 4321918527391410323UL), () => _ufle12jhs77_BG_Next = null));
	private static readonly BGClass_ImportedFonts.Factory _factory0_PFS = new BGClass_ImportedFonts.Factory();
	private static readonly BGClass_ImportedFontsCommit.Factory _factory1_PFS = new BGClass_ImportedFontsCommit.Factory();
	private BGClass_ImportedFontsCommit() : base(MetaDefault)
	{
	}
	private BGClass_ImportedFontsCommit(BGId id) : base(MetaDefault, id)
	{
	}
	private BGClass_ImportedFontsCommit(BGMetaEntity meta) : base(meta)
	{
	}
	private BGClass_ImportedFontsCommit(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static BGClass_ImportedFontsCommit FindEntity(Predicate<BGClass_ImportedFontsCommit> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((BGClass_ImportedFontsCommit) entity)) as BGClass_ImportedFontsCommit;
	}
	public static List<BGClass_ImportedFontsCommit> FindEntities(Predicate<BGClass_ImportedFontsCommit> filter, List<BGClass_ImportedFontsCommit> result=null, Comparison<BGClass_ImportedFontsCommit> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<BGClass_ImportedFontsCommit> action, Predicate<BGClass_ImportedFontsCommit> filter=null, Comparison<BGClass_ImportedFontsCommit> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((BGClass_ImportedFontsCommit) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((BGClass_ImportedFontsCommit) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((BGClass_ImportedFontsCommit)e1,(BGClass_ImportedFontsCommit)e2));
	}
	public static BGClass_ImportedFontsCommit GetEntity(BGId entityId) => (BGClass_ImportedFontsCommit) MetaDefault.GetEntity(entityId);
	public static BGClass_ImportedFontsCommit GetEntity(int index) => (BGClass_ImportedFontsCommit) MetaDefault[index];
	public static BGClass_ImportedFontsCommit GetEntity(string entityName) => (BGClass_ImportedFontsCommit) MetaDefault.GetEntity(entityName);
	public static BGClass_ImportedFontsCommit NewEntity() => (BGClass_ImportedFontsCommit) MetaDefault.NewEntity();
	public static BGClass_ImportedFontsCommit NewEntity(BGId entityId) => (BGClass_ImportedFontsCommit) MetaDefault.NewEntity(entityId);
	public static BGClass_ImportedFontsCommit NewEntity(Action<BGClass_ImportedFontsCommit> callback)
	{
		return (BGClass_ImportedFontsCommit) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((BGClass_ImportedFontsCommit)entity)));
	}
}
#pragma warning restore 414
