using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace sarisari
{
	[AddComponentMenu("BansheeGz/Generated/BGGo_ImportedFontsCommit")]
	public partial class BGGo_ImportedFontsCommit : BGEntityGo
	{
		public override BGMetaEntity MetaConstraint => MetaDefault;
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5698365174517956776UL,4377561417327406011UL), () => _metaDefault = null));
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public new System.String name
		{
			get => _name[Entity.Index];
			set => _name[Entity.Index] = value;
		}
		public System.String FilePath
		{
			get => _FilePath[Entity.Index];
			set => _FilePath[Entity.Index] = value;
		}
		public System.Int32 Next
		{
			get => _Next[Entity.Index];
			set => _Next[Entity.Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5165186123815129994UL, 3682541195757062075UL), () => _ufle12jhs77_name = null));
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_FilePath;
		public static BansheeGz.BGDatabase.BGFieldString _FilePath => _ufle12jhs77_FilePath ?? (_ufle12jhs77_FilePath = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5378120277811624140UL, 4082224575315318207UL), () => _ufle12jhs77_FilePath = null));
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Next;
		public static BansheeGz.BGDatabase.BGFieldInt _Next => _ufle12jhs77_Next ?? (_ufle12jhs77_Next = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5444389343373439259UL, 4321918527391410323UL), () => _ufle12jhs77_Next = null));
	}
}
