using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

namespace sarisari
{
	[AddComponentMenu("BansheeGz/Generated/BGGo_ImportedFonts")]
	public partial class BGGo_ImportedFonts : BGEntityGo
	{
		public override BGMetaEntity MetaConstraint => MetaDefault;
		private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
		public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5394091832305173659UL,15825802688521098940UL), () => _metaDefault = null));
		public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
		public new System.String name
		{
			get => _name[Entity.Index];
			set => _name[Entity.Index] = value;
		}
		public System.String FilePath
		{
			get => _FilePath[Entity.Index];
			set => _FilePath[Entity.Index] = value;
		}
		public System.Int32 Next
		{
			get => _Next[Entity.Index];
			set => _Next[Entity.Index] = value;
		}
		private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
		public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5491788736441075098UL, 9942495857176704684UL), () => _ufle12jhs77_name = null));
		private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_FilePath;
		public static BansheeGz.BGDatabase.BGFieldString _FilePath => _ufle12jhs77_FilePath ?? (_ufle12jhs77_FilePath = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5012169299209808125UL, 11947896336987441076UL), () => _ufle12jhs77_FilePath = null));
		private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Next;
		public static BansheeGz.BGDatabase.BGFieldInt _Next => _ufle12jhs77_Next ?? (_ufle12jhs77_Next = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5233077079295538586UL, 4239875578567192449UL), () => _ufle12jhs77_Next = null));
	}
}
